package es.tributasenasturias.servicios.ibi.deuda;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.tributasenasturias.servicios.ibi.deuda.contextoLlamadas.CallContext;
import es.tributasenasturias.servicios.ibi.deuda.contextoLlamadas.CallContextConstants;
import es.tributasenasturias.servicios.ibi.deuda.contextoLlamadas.CallContextManager;
import es.tributasenasturias.servicios.ibi.deuda.exceptions.IBIException;
import es.tributasenasturias.servicios.ibi.deuda.exceptions.MensajesException;
import es.tributasenasturias.servicios.ibi.deuda.mensajes.MensajesAplicacion;
import es.tributasenasturias.servicios.ibi.deuda.mensajes.MensajesFactory;
import es.tributasenasturias.servicios.ibi.deuda.preferencias.Preferencias;
import es.tributasenasturias.servicios.ibi.deuda.preferencias.PreferenciasException;
import es.tributasenasturias.servicios.ibi.deuda.preferencias.PreferenciasFactory;
import es.tributasenasturias.servicios.ibi.deuda.procesadores.InterfazDeudaIBI;
import es.tributasenasturias.servicios.ibi.deuda.util.Utils;
import es.tributasenasturias.utils.log.LogFactory;
import es.tributasenasturias.utils.log.Logger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "SOAPGateway", serviceName = "SOAPGatewayService", targetNamespace = "http://inti.notariado.org/XML/CD", wsdlLocation = "/wsdls/deudas-soap-gateway.wsdl", endpointInterface = "es.tributasenasturias.servicios.ibi.deuda.SOAPGateway")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain (file="HandlerChain.xml")
public class SOAPGatewayService_SOAPGatewayImpl implements SOAPGateway {

	public SOAPGatewayService_SOAPGatewayImpl() {
	}

	@Resource WebServiceContext wcontext;
	/**
	 * 
	 * @param partRequest
	 * @return returns es.tributasenasturias.ibi.deuda.MESSAGERESPONSE
	 */
	public MESSAGERESPONSE process(MESSAGEREQUEST partRequest) {
		Logger log=null;
		try {
			CallContext contexto=CallContextManager.newCallContext();
			Preferencias pref= (Preferencias) wcontext.getMessageContext().get(CallContextConstants.PREFERENCIAS);
			if (pref==null)
			{
				pref = PreferenciasFactory.newInstance();
			}
			String idLlamada = (String) wcontext.getMessageContext().get(CallContextConstants.IDSESION);
			if (idLlamada == null)
			{
				idLlamada = Utils.getIdLlamada();
			}
			log = LogFactory.newLogger(pref.getModoLog(), pref.getFicheroLogAplicacion(), "Sesión::"+idLlamada);
			//Mensajes de aplicación, muy importante.
			MensajesAplicacion mensajes = (MensajesAplicacion) wcontext.getMessageContext().get(CallContextConstants.MENSAJES);
			if (mensajes==null)
			{
				mensajes = MensajesFactory.newMensajesAplicacion(pref.getFicheroMensajesAplicacion(), pref.getFicheroMapeoMensajes());
			}
			contexto.setItem(CallContextConstants.IDSESION, idLlamada);
			contexto.setItem(CallContextConstants.PREFERENCIAS, pref);
			contexto.setItem(CallContextConstants.LOG, log);
			contexto.setItem(CallContextConstants.MENSAJES, mensajes);
			InterfazDeudaIBI procesador=SelectorOperacion.seleccionaProcesador(partRequest, contexto);
			return procesador.process(partRequest);
		} catch (IBIException e) {
			if (log!=null)
			{
				log.error("Error en la ejecución de proceso de consulta o pago de deuda de IBI:"+e.getMessage(), e);
			}
			throw new WebServiceException ("Error en la ejecución de proceso de petición de IBI.");
		} catch (PreferenciasException e) {
			if (log!=null)
			{
				log.error("Error en la ejecución de proceso de consulta o pago de deuda de IBI:"+e.getMessage(), e);
			}
			throw new WebServiceException ("Error en la ejecución de proceso de petición de IBI.");
		} catch (MensajesException e)
		{
			if (log!=null)
			{
				log.error("Error en la ejecución de proceso de consulta o pago de deuda de IBI:"+e.getMessage(), e);
			}
			throw new WebServiceException ("Error en la ejecución de proceso de petición de IBI.");
		}
	}

}
