package es.stpa.plusvalias;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.stpa.plusvalias.preferencias.Preferencias;
import es.stpa.plusvalias.preferencias.PreferenciasException;
import es.stpa.plusvalias.soap.SOAPUtils;
import es.tributasenasturias.log.TributasLogger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "SOAPGateway", serviceName = "SOAPGatewayService", targetNamespace = "http://ancert.notariado.org/XML/Plusvalias/Liquidacion", wsdlLocation = "/wsdls/WsdlAncertPlusvalias.wsdl", endpointInterface = "es.stpa.plusvalias.SOAPGateway")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain (file="HandlerChain.xml")
public class SOAPGatewayService_SOAPGatewayImpl implements SOAPGateway {

	@Resource WebServiceContext wcontext;
	
	public SOAPGatewayService_SOAPGatewayImpl() {
	}

	/**
	 * 
	 * @param parameters
	 * @return returns es.stpa.plusvalias.MESSAGERESPONSE
	 */
	public MESSAGERESPONSE process(MESSAGEREQUEST parameters) {
		TributasLogger log= null;
		boolean esCalculo=false;
		boolean esListaExenciones=false;
		boolean esPago=false;
		MESSAGERESPONSE response= new MESSAGERESPONSE();
		try {
			Preferencias pref= (Preferencias) wcontext.getMessageContext().get(Constantes.PREFERENCIAS);
			if (pref==null)
			{
				pref = new Preferencias();
			}
			String idLlamada = (String) wcontext.getMessageContext().get(Constantes.IDSESION);
			if (idLlamada == null)
			{
				idLlamada = SOAPUtils.getIdLlamada();
			}
			log = new TributasLogger(pref.getModoLog(), pref.getDirectorioRaizLog(),pref.getFicheroLogAplicacion(), "Sesión::"+idLlamada);
			
			//Comprobamos qué mensaje nos han pasado
			if (parameters.getCALCULOLIQUIDACION()!=null){
				esCalculo=true;
				log.info("INICIO DEL PROCESO DE CÁLCULO DE LIQUIDACIÓN DE PLUSVALÍA");
				CALCULOLIQUIDACION respuestaAncert = new CALCULOLIQUIDACION();
				CalculoPlusvaliaImpl impl= new CalculoPlusvaliaImpl(pref, log, idLlamada);
				CALCULOLIQUIDACION.REPLY respuestaCalculo=impl.calcularLiquidacion(parameters.getCALCULOLIQUIDACION().getREQUEST());
				respuestaAncert.setREPLY(respuestaCalculo);
				response.setCALCULOLIQUIDACION(respuestaAncert);
				
			} else if (parameters.getEXENCIONESBONIFICACIONES()!=null){
				esListaExenciones=true;
				log.info("INICIO DEL PROCESO DE RECUPERACIÓN DE EXENCIONES Y BONIFICACIONES");
				EXENCIONESBONIFICACIONES respuestaAncert = new EXENCIONESBONIFICACIONES();
				ExencionBonificacionImpl impl= new ExencionBonificacionImpl(pref, log, idLlamada);
				respuestaAncert.setREPLY(impl.obtenerListaExenciones(parameters.getEXENCIONESBONIFICACIONES().getREQUEST()));
				response.setEXENCIONESBONIFICACIONES(respuestaAncert);
			} else if (parameters.getPAGOLIQUIDACION()!=null){
				esPago=true;
				log.info("INICIO DEL PROCESO DE PAGO Y PRESENTACIÓN DE LIQUIDACIÓN DE PLUSVALÍA");
				//Intentamos extraer la escritura
				byte[] escritura= (byte[])wcontext.getMessageContext().get(Constantes.ESCRITURA);
				
				PAGOLIQUIDACION respuesta= new PAGOLIQUIDACION();
				PagoPresentacionImpl impl= new PagoPresentacionImpl(pref, log, idLlamada);
				PAGOLIQUIDACION.REPLY respuestaPago= impl.presentarLiquidacion(parameters.getPAGOLIQUIDACION().getREQUEST(), escritura);
				respuesta.setREPLY(respuestaPago);
				response.setPAGOLIQUIDACION(respuesta);
			} else {
				throw new WebServiceException("Error grave, no se ha recibido ningún mensaje de tipo CALCULOLIQUIDACION, EXENCIONESBONIFICACIONES o PAGOLIQUIDACION");
			}
		} catch (PreferenciasException e) {
			if (log!=null)
			{
				log.error("Error en la ejecución de proceso:"+e.getMessage(), e);
			}
			throw new WebServiceException ("Error en la ejecución de proceso.",e);
		} catch (Exception e){
			if (log!=null)
			{
				log.error("Error grave en la ejecución de proceso :"+e.getMessage(), e);
			}
			throw new WebServiceException ("Error en la ejecución de proceso.",e);
		}
		finally {
			if (log!=null){
				if (esListaExenciones){
					log.info("FIN DEL PROCESO DE RECUPERACIÓN DE EXENCIONES Y BONIFICACIONES");
				} else if (esCalculo){
					log.info("FIN DEL PROCESO DE CÁLCULO DE LIQUIDACIÓN DE PLUSVALÍA");
				} else if (esPago) {
					log.info("FIN DEL PROCESO DE PAGO Y PRESENTACIÓN DE LIQUIDACIÓN DE PLUSVALÍA");
				}
			}
		}
		return response;
	}

}
